{% set name = "cleverdict" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cleverdict-{{ version }}.tar.gz
  sha256: e8f3ff95885e311bbb42c59988dd9c2fdb1ce1345a2037db1da26567cded7fb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - cleverdict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Pfython/cleverdict
  summary: A JSON-friendly data structure which allows both object attributes and dictionary keys and values to be used simultaneously and interchangeably.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
